---
- name: Install docker, kubeadm
  hosts: k8s-machines
  remote_user: vagrant
  become: yes

  tasks:
  - name: install MC
    apt:
      name: mc
      state: present

  - name: Disable UFW
    community.general.ufw:
      state: disabled
      policy: allow